name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for the raising this Issue, someone will get back to you asap'
        pr-message: 'Thanks for your wonderful contribution, someone will be reviewing your PR'
